add host and ubuntu gpu image
yunionio/service-images pull request #1
Opened 2019-05-15 15:10 UTC by Zexi

- 定义 centos 7.6 host 和 ubuntu 18.04 gpu 的镜像制作
- 添加 ./tools/create-image.sh 使用 zerofree 和 qemu-img 压缩 packer 做好的镜像

/cc @swordqiu @yousong @wanyaoqi 具体使用方法参考 README

2019-05-16 01:54 UTC, yousong requested changes

2019-05-16 01:54 UTC, yousong commented on scripts/k8s/k8s-config.sh
> +    if [ $? -eq 0 ]; then
`$?`会有问题。可以用`"EOF"`，避免var subst

2019-05-16 01:54 UTC, yousong commented on scripts/ubuntu/remove-netplan.sh
> +    networkd-dispatcher systemd-networkd-wait-online
直接用`mask --now`就可以，stop, disable都可以不用

2019-05-16 01:54 UTC, yousong commented on scripts/host/post-config.sh
> +systemctl enable yunion
这个名为`yunion`的服务是做什么用的？

2019-05-16 01:54 UTC, yousong commented on host/http/centos7-ks.cfg
> +user --name yunion --password yunion --plaintext
建议默认的密码用一个值。作为默认的密码，强度都是一样的，减少记忆成本

2019-05-16 01:54 UTC, yousong commented on Makefile
> +	-rm -rf $(HOST_IMG)
建议在这里加3个目录检查，

`[ -d contrib/cloud ]`

2019-05-16 02:18 UTC, yousong commented
/hold

2019-05-16 03:03 UTC, Zexi commented on scripts/host/post-config.sh
> +systemctl enable yunion
物理机转换到宿主机用的，在 /etc/init.d/yunion 里面，这里会调用 checkconfig 启动

2019-05-16 03:03 UTC, Zexi commented on host/http/centos7-ks.cfg
> +user --name yunion --password yunion --plaintext
ok

2019-05-16 03:14 UTC, yousong commented on scripts/host/post-config.sh
> +systemctl enable yunion
取名太随意 ;)

2019-05-16 08:47 UTC, zexi commented
/hold cancel
@swordqiu @yousong 改进了下，使用脚本来协作 host 镜像的制作，包括下载 iso，准备环境，制作压缩的镜像。
host 相关的 init 脚本放在了 *scripts/host/os-init* 里面。

2019-05-16 09:55 UTC, swordqiu commented on scripts/host/post-config.sh
> +chown -R yunion:yunion /opt/yunion
执行一下 /opt/yunion/clean-template.sh

2019-05-16 09:55 UTC, swordqiu commented on scripts/host/post-config.sh
> +systemctl enable yunion
chkconfig yunion on?
yunion放在/etc/init.d里面，实时SysV的启动脚本

2019-05-16 09:55 UTC, swordqiu commented on gpu/ubuntu-1604.json
> +        "ssh_password": "123@yunion",
ubuntu是否需要删除/etc/ssh/*.key? 然后放入初始化脚本，在系统启动的时候自动生成 ssh server host keys

2019-05-16 09:55 UTC, swordqiu commented on scripts/host/autoupdate-config.sh
> +curl -OL https://iso.yunion.cn/yumrepo-2.8/yunion-autoupdate-2.8.20190415.1-19041516.x86_64.rpm
对了，为了让autoupdate工作，还得放几个iso里的文件,download.sh, upgrade.sh, version, versions.json，执行 /opt/yunion/patch.sh

2019-05-16 09:55 UTC, swordqiu commented on scripts/host/autoupdate-config.sh
> +curl -OL https://iso.yunion.cn/yumrepo-2.8/yunion-autoupdate-2.8.20190415.1-19041516.x86_64.rpm
https://git.yunion.io/projects/CLOUD/repos/yunionos-init/pull-requests/5/overview

2019-05-16 13:01 UTC, Zexi commented on scripts/host/autoupdate-config.sh
> +curl -OL https://iso.yunion.cn/yumrepo-2.8/yunion-autoupdate-2.8.20190415.1-19041516.x86_64.rpm
都改了

2019-05-16 13:03 UTC, Zexi commented on gpu/ubuntu-1604.json
> +        "ssh_password": "123@yunion",
已改，会调用 ./scripts/{ubuntu,centos}/clean-sshkeys.sh 来做这个事情

2019-05-16 13:03 UTC, Zexi commented on scripts/host/post-config.sh
> +chown -R yunion:yunion /opt/yunion
改了

2019-05-16 13:05 UTC, Zexi commented on scripts/k8s/k8s-config.sh
> +    if [ $? -eq 0 ]; then
没太明白，能具体说下怎么改这行吗？

2019-05-16 13:05 UTC, Zexi commented on scripts/ubuntu/remove-netplan.sh
> +    networkd-dispatcher systemd-networkd-wait-online
已改

2019-05-16 13:16 UTC, swordqiu commented
/approve

2019-05-16 13:22 UTC, swordqiu approved these changes

2019-05-17 02:16 UTC, Zexi commented
/lgtm

2019-05-17 02:22 UTC, wanyaoqi commented
/lgtm
/approve

2019-05-17 02:22 UTC, merged